module.exports = Object.freeze({
    SET_PORT_EVENT: 'setPort',
    L0_SWITCH_ID: 'Led0Switch',
    L1_SWITCH_ID: 'Led1Switch',
    S0_READ_EVENT: 'readS0',
    S1_READ_EVENT: 'readS1',
    L0_PWM_EVENT: 'setPwmL0',
    L1_PWM_EVENT: 'setPwmL1',
    PWM_VALUE: 'pwm-value',
    L0_PULSE_EVENT: 'setPulseL0',
    L1_PULSE_EVENT: 'setPulseL1',
    PULSE_VALUE: 'pulse-value',
    ALL_OFF_EVENT: 'turnAllOff',
    MAC_PLATFORM: 'darwin',
    NOT_CONNECTED_ARDUINO: 'Arduino no conectado',
    PORT_ARDUINO_LABEL: 'port:Arduino',
    STATUS_BUTTON_START: 9,
    STATUS_BUTTON_END: 15,
    BUTTON_STRING: 'Button', 
    SAVE_EVENT: 'saveEEPROM',
    SERIAL_MESSAGE_EVENT: 'serialMessage'
});